# fly.toml app configuration file generated for langchain-fortune-teller on 2025-09-05T12:41:27+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'langchain-fortune-teller'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
